version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      - npm install -g htmlhint

  pre_build:
    commands:
      - echo "Checking HTML files..."
      - htmlhint "**/*.html"

  build:
    commands:
      - echo "Validating HTML..."

artifacts:
  files:
    - '**/*'
