version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      - npm install -g htmlhint

  pre_build:
    commands:
      - htmlhint "**/*.html"

  build:
    commands:
      - echo "HTML validation successful..."

artifacts:
  files:
    - '**/*'
